name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-11

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Go back
        run: |
           cd NYTimesPOC
           echo "Here below:"
           ls ${{ github.workspace }}
      - name: Build
        run: xcodebuild test -scheme NYTimesPOC -project NYTimesPOC.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.0' | xcpretty && exit ${PIPESTATUS[0]}
